name: Build Nix Packages

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: Git commit or branch
        required: true
      packages:
        description: Packages to build, space separated
        required: true
      check:
        description: Add "--check"
        type: choice
        required: false
        default: false
        options:
          - "false"
          - "true"
      os:
        description: Operating system
        required: true
        type: choice
        options:
          # https://github.com/actions/virtual-environments#available-environments
          - macos-latest
          - macos-latest-large
          - ubuntu-latest
          - ubuntu-latest-arm
jobs:
  parse-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Parse packages
        id: parse-packages
        run: |
          PACKAGES=$(printf %s "${{ github.event.inputs.packages }}" | jq -cRs 'split(" ")')
          echo "PACKAGES: $PACKAGES"
          echo ::set-output name=packages::${PACKAGES}
          echo "packages=${PACKAGES}" >> $GITHUB_OUTPUT
    outputs:
      packages: ${{ steps.parse-packages.outputs.packages }}
  build:
    runs-on: ${{ github.event.inputs.os }}
    needs:
      - parse-inputs
    strategy:
      matrix:
        package: ${{ fromJSON(needs.parse-inputs.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref }}
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: austinbutler
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build package
        run: nix-build -A ${{ matrix.package }} $([[ "${{ github.event.inputs.check }}" == "true" ]] && printf %s '--check')
