name: Build Nix Packages

on:
  #push:
  #  branches: [ ci-my-pkgs ]
  #pull_request:
  #  branches: [ ci-my-pkgs ]

  workflow_dispatch:
    inputs:
      git_ref:
        description: Git commit or branch
        required: true
      packages:
        description: Packages to build, space separated
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.git_ref}}
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: build packages
        run: nix-build -A ${{github.event.inputs.packages}}
